icecc: Import improved version from oe-core master and always inherit
:Release Notes:
Fix icecc.bbclass failing with:
    ERROR: recipe-name NULL prefix
when it's used with an empty TARGET_PREFIX. Always inherit it, but have
it be disabled by default.

NOTE: People already using icecc need to update their webos-local.conf:
Add:    ICECC_DISABLED = ""
Remove: INHERIT*icecc*

:Detailed Notes:
Add 3 extra patches which aren't applied yet:
baee0c4 WIP: icecc.bbclass: Exclude few variables causing different
        signatures for native and allarch recipes
21268fb WIP: icecc.bbclass: use bb.utils.which also for 'as'
d060a05 icecc: Don't replace non-empty PARALLEL_MAKE with empty
        ICECC_PARALLEL_MAKE

http://lists.openembedded.org/pipermail/openembedded-core/2013-November/087044.html
http://lists.openembedded.org/pipermail/openembedded-core/2013-December/087249.html
http://lists.openembedded.org/pipermail/openembedded-core/2013-December/087250.html

Backport following commits from oe-core master (1.6)
e220c8e icecc.bbclass: Fix whitespace, improve comment
b325e46 classes/icecc: fix typos in header comments
a956f9d icecc: Disable icecc for allarch recipes
7ed7aa3 icecc: Use bb.utils.which instead of calling which
8a30be8 icecc: Fix race condition when packaging toolchain
d2735ac icecc: Add package whitelist
b28bae3 icecc: Support shell evaluation of KERNEL_CC
bb1366c icecc: Enable icecc also for install step
365dec5 icecc: Add dummy python version of set_icecc_env
0f7dc96 icecc: Add blacklist vars to BB_HASHBASE_WHITELIST
6d27356 icecc: Reduce verbosity with empty PARALLEL_MAKE
0adea17 icecc: Log reason in error cases

Allarch recipes cannot use compiler at all (even the local one) so
there is no point of using icecc for them.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Build Notes:
This change will invalidate all shared-state signatures.

:Issues Addressed:
[GF-44050] allarch components have different signatures with different
           tcmode
[GF-45392] icecc does not work

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: If647a1388a1a07fc8a433a281b6f311079010db0
Reviewed-on: https://g2g.palm.com/4060
Reviewed-by: DCO Verification
Build: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Build Verification
Reviewed-by: Susan Montooth <susan.montooth@lge.com>