boost: Remove .bbappend, resolved in oe-core
:Release Notes:
This issue is now resolved in oe-core/dylan

:Detailed Notes:
This .bbappend needs to be removed before we upgrade oe-core
revision (or atomically with it), otherwise build fails with:
ERROR: The function get_boost_parallel_make defined in
boost_1.53.0.bbappend was already declared in boost.inc.
BitBake has a global python function namespace so shared functions
should be declared in a common include file rather than being
duplicated, or if the functions are different, please use different
function names.

:Testing Performed:
No change in build

:QA Notes:
No change in image

:Issues Addressed:
[GF-6959] boost-1.53 build segfaults when building with -j greater than 64

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: Id0b26f2bdc2baeb474ae378e859e88a93d25324c
Reviewed-on: https://g2g.palm.com/2824
Reviewed-by: Build Verification
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Herb Kuta <herb.kuta@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>
Tested-by: Susan Montooth <susan.montooth@lge.com>