enyo-1.0: Add branch parameter, introduce ENYOJS_GIT_REPO_COMPLETE
:Release Notes:
SRC_URI was missing WEBOS_GIT_BRANCH variable, so branch specified by
WEBOS_VERSION and used by SRC_URI didn't match causing this QA ERROR:
  ERROR: QA Issue: Branch is set in WEBOS_VERSION '@128' for recipe
    'enyo-1.0' (file 'meta-webos/recipes-webos/frameworks/enyo-1.0.bb')
    as well as in SRC_URI 'master' and they don't match
Fix it by using ENYOJS_GIT_REPO_COMPLETE and then explicitly set branch
parameter to match reality.

:Detailed Notes:

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[ES-571] Decide how to handle multiple levels of branched submissions
         of components
[BHV-9439] CCC: Fix submissions bbclasses to support pre-submission and
           multiple levels of branched submissions

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: Ic11b1c747af639481d22b1a80cca1f1e0100c40c
Reviewed-on: https://g2g.palm.com/5896
Reviewed-by: DCO Verification
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>