webos-repositories.inc: Use http when accessing github.com
:Release Notes:
Fetching over https:// is currently broken and doesn't make much sense
as we're checking the checksums after download anyway.

:Detailed Notes:
Fixes following issue in builds without premirror:
WARNING: Failed to fetch URL
  https://github.com/downloads/isis-project/WebKit/WebKit_0.54s.zip,
  attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, output:
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert
  handshake failure
Unable to establish SSL connection.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>

Change-Id: Ia6c9b9c26d723254a4e83451034b778fbdff41e7
Reviewed-on: https://g2g.palm.com/6162
Reviewed-by: DCO Verification
Build: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Build Verification
Reviewed-by: Susan Montooth <susan.montooth@lge.com>
Tested-by: Susan Montooth <susan.montooth@lge.com>