keyboard-efigs: Add missing dependencies
* qmake-webos-native for webos_qmake
* libpbnjson for ../include/JSONUtils.h:23:23:
  fatal error: pbnjson.hpp: No such file or directory

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@palm.com>
Change-Id: I71e909006b4380959034e672114c469e904dfcab
Reviewed-on: http://g2g.palm.com/1278
Reviewed-by: Build Verification
Reviewed-by: Susan Montooth <susan.montooth@palm.com>
Tested-by: Susan Montooth <susan.montooth@palm.com>