webos.inc: Fix perf signature changing when perl was or wasn't built
:Release Notes:
Fixes error sometimes shown when generating signatures.

:Detailed Notes:
Without this bitbake -S perf shows following error:
ERROR: Bitbake's cached basehash does not match the one we just generated
  (/OE/oe-core/meta/recipes-kernel/perf/perf.bb.do_package)!
if you run it twice, once without perl in sysroot and once with perl
already built

:Testing Performed:
Verified with bitbake -S.

:QA Notes:
No change to image.

:Issues Addressed:
[GF-42606] Ongoing metadata improvement/cleanup work

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: Ie5acbe75c624fa292ead93bb850fd93e529705bb
Reviewed-on: https://g2g.palm.com/4088
Reviewed-by: DCO Verification
Build: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>