webos-image: icecc-create-env=1.0.1
:Release Notes:
Update script to include fixes necessary for the correct compilation of
some components.

:Detailed Notes:
Errors similiar to the following appeared due to incorrect handling of
toolchain binaries for distributed compilation by ICECC. In order to
take full advantage ICECC, we need to resolve those compilation errors
instead of supressing them with no-use-linker-plugin.

   gxx: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found

The original script was modified for use in OE build environment.

:Testing Performed:
Built full image from source. Ran MiniBAT on the resulting image.

:QA Notes:

:Issues Addressed:
[ANG-787] ICECC deployment in part of build infrastructure
[ANG-789] CCC: Enable usage of ICECC as part of build infrastructure

Open-webOS-DCO-1.0-Signed-off-by: Iyad Qumei <iyad.qumei@lge.com>

Change-Id: Ia0bbf07a78a1b48c906b99249540900330c3438b
Reviewed-on: https://g2g.palm.com/4120
Reviewed-by: DCO Verification
Reviewed-by: Iyad Qumei <iyad.qumei@lge.com>
Tested-by: Iyad Qumei <iyad.qumei@lge.com>
Reviewed-by: Keith Derrick <keith.derrick@lge.com>
Reviewed-by: Alexander Irhin <alexander.irhin@lge.com>