bbclasses, recipes: use 4 spaces in python tasks
* replace tabs with 4 spaces in python tasks
* shell tasks should use tabs according to yocto styleguide,
  but that's not fatal and in meta-webos there is a lot of shell
  code indented by 4 spaces (which is better, because it's consistent
  with python tasks)
* newer oe-core is using 4 spaces and python code will fail with IndentationError
  when we prepend tab indentation to such task (e.g. populate_packages, clean)
  NOTE: Error during finalise of recipe.bb
  ERROR: ExpansionError during parsing recipe.bb:
    Failure expanding variable populate_packages:
    IndentationError: unindent does not match any outer indentation level (<string>, line 4)
* there is also check in bitbake:
  WARNING: Variable populate_packages contains tabs, please remove these (recipe.bb)

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Change-Id: I50a6dc28ed8cdafae8a8465aa99b51d9e626d4a8
Reviewed-on: http://g2g.palm.com/1102
Reviewed-by: Martin Jansa <martin.jansa@palm.com>
Tested-by: Martin Jansa <martin.jansa@palm.com>
Reviewed-by: Susan Montooth <susan.montooth@palm.com>