qt4-webos: Explicitly disable sqlite, openvg and enable openssl
:Release Notes:
All dependencies should be explicitly enabled or disabled

:Detailed Notes:
SQLite2 support is autodetected from sysroot and enabled if
sqlite was built before qt4-webos. OpenSSL support is needed
otherwise webappmanager build can fail when it's trying to use
webkit-webos built with openssl enabled in sysroot with qt4-webos
without openssl enabled:
webappmanager 3.0.0-3-r5 do_compile
sysroots/qemux86/usr/lib/libQtWebKit.so: undefined reference to `QSslSocket::QSslSocket(QObject*)'
sysroots/qemux86/usr/lib/libQtWebKit.so: undefined reference to `QSslError::error() const'
sysroots/qemux86/usr/lib/libQtWebKit.so: undefined reference to `QSslSocket::connectToHostEncrypted(QString const&, unsigned short, QFlags<QIODevice::OpenModeFlag>)'
sysroots/qemux86/usr/lib/libQtWebKit.so: undefined reference to `QSslSocket::staticMetaObject'
collect2: error: ld returned 1 exit status

:Testing Performed:
Build tested only

:QA Notes:
No change in image

:Issues Addressed:
[GF-9365] Explicitly enable or disable autodetected dependencies

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: I4ac419a58a2a93bbbf3f027788a8af0dc6eae370
Reviewed-on: https://g2g.palm.com/2905
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Build Verification
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>