webos.inc: Fix parsing issues caused by WEBOS_DISTRO_BUILD_CODENAME
:Release Notes:
Now with branch name included in image names it can cause parsing
or build errors when the branch contains some characters with special
meaning in shell. Remove at least the most common '()/'.

:Detailed Notes:
Noticed when builds started to fail with build-webos branch set to
'(nobranch)':

ERROR: ExpansionError during parsing
/meta-webos/recipes-core/images/webos-image.bb: Failure expanding
variable build_boot_dd: ShellSyntaxError:
LexToken(TOKEN,'nobranch',0,0)
followed by:
  LexToken(RPARENS,')',0,0)
  LexToken(TOKEN,'-20140121132526.hdddirect',0,0)
  LexToken(NEWLINE,'\n',0,0)
  LexToken(NEWLINE,'\n',0,0)
  LexToken(TOKEN,'install',0,0)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[ANG-329] Ongoing metadata improvement/cleanup work

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>

Change-Id: I2512fbefac2803c8d15f292d7d680402567479ac
Reviewed-on: https://g2g.palm.com/4458
Reviewed-by: DCO Verification
Build: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Build Verification
Reviewed-by: Herb Kuta <herb.kuta@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>