alsa-plugins: Disable a52 plugin
:Release Notes:
We don't have dependency on libav and sometimes it's autodetected or
build is failing with undefined reference to av_free().

:Detailed Notes:
See http://mailman.alsa-project.org/pipermail/alsa-devel/2011-January/035894.html
for details.

:Testing Performed:
Build doesn't fail with undefined reference anymore

:QA Notes:
No change in image

:Issues Addressed:
[GF-8548] alsa-plugins autodetect libav and sometimes fail to build a52 plugin

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Change-Id: I8381300feccc439e2a3e05de8e4b31f84987c0ce
Reviewed-on: https://g2g.palm.com/2812
Reviewed-by: Build Verification
Reviewed-by: Martin Jansa <Martin.Jansa@lge.com>
Tested-by: Martin Jansa <Martin.Jansa@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>