db8: Add missing dependency on boost
:Release Notes:
Last submission upgrade introduced new dependency on boost without
adding boost into DEPENDS.

:Detailed Notes:
Fails without boost built in sysroot:
| In file included from db8/2.0.0-76-r13/git/inc/db-luna/leveldb/MojDbLevelQuery.h:24:0,
|                  from db8/2.0.0-76-r13/git/src/db-luna/leveldb/MojDbLevelEngine.cpp:26:
| db8/2.0.0-76-r13/git/inc/db-luna/leveldb/MojDbLevelCursor.h:28:46:
  fatal error: boost/smart_ptr/scoped_ptr.hpp: No such file or directory
| compilation terminated.

:Testing Performed:
Builds OK after building boost.

:QA Notes:
No change in image

:Issues Addressed:
[GF-9365] Explicitly enable or disable autodetected dependencies

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@lge.com>

Change-Id: If6b07f4ebc138224b690654579a30b7e8cf5bd85
Reviewed-on: https://g2g.palm.com/3068
Reviewed-by: Build Verification
Reviewed-by: Susan Montooth <susan.montooth@lge.com>
Tested-by: Susan Montooth <susan.montooth@lge.com>