webos.conf: Remove comments with trailing backslash
* with newer bitbake (which has this commit
  https://github.com/openembedded/bitbake/commit/79c00fabe08b4c210a3bd81cfaffbc47ffdc2e2b)
  it fails to parse:
  ERROR: There is a confusing multiline, partially commented
  expression on line 114 of file
  meta-webos/conf/distro/webos.conf (
  #            Ubuntu 10.04.4 LTS \n
  #            Ubuntu 11.10 \n
  #            Fedora release 15 (Lovelock) \n
  #            Fedora release 16 (Verne) \n
  #            Fedora release 17 (Beefy Miracle) \n
  #            CentOS release 5.6 (Final) \n
  #            CentOS release 5.7 (Final) \n
  #            CentOS release 6.2 (Final) \n
  #            Debian GNU/Linux 6.0.4 (squeeze) \n
  #            openSUSE 11.4 \n
  #            openSUSE 12.1 \n \).
  Please clarify whether this is all a comment or should be parsed.

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <martin.jansa@palm.com>
Change-Id: I59096698f95a8dd78fa44633df9c577319112c89
Reviewed-on: http://g2g.palm.com/1426
Reviewed-by: Martin Jansa <martin.jansa@palm.com>
Tested-by: Martin Jansa <martin.jansa@palm.com>
Reviewed-by: Build Verification
Reviewed-by: Susan Montooth <susan.montooth@palm.com>